#!/usr/bin/env bash
# Reproduces every result of the PR 5 (fast Gaussian resampling) counterexample hunt.
# Requirements: python3, mpmath, python-flint (pip install --user --break-system-packages python-flint mpmath)
# Total runtime about 25-35 minutes on one core; peak memory well under 1 GB.
set -u
cd "$(dirname "$0")"
mkdir -p logs
R="${REPO:?set REPO to a clone of CrocSwap/integer-mult-bounds with PR refs fetched as prs/N}"
PIN=d3d370c34937503bd3fa63c83d505a05e8e50893

echo "== pin check"; git -C "$R" rev-parse refs/remotes/prs/5 | tee logs/pin.log
[ "$(git -C "$R" rev-parse refs/remotes/prs/5)" = "$PIN" ] || echo "WARNING: prs/5 moved from pinned $PIN" | tee -a logs/pin.log

echo "== T1 exact identities/constants";  nice python3 -u t1_exact.py      > logs/t1_exact.log 2>&1;    tail -3 logs/t1_exact.log
echo "== T2 powers of E / corollary";     nice python3 -u t2_powers.py 36 2,3,4,5,6,8 40 400 50,51 64,65 100,101 128,129 200,201 97,121 101,126 199,248 150,187 255,256 > logs/t2_powers.log 2>&1; tail -4 logs/t2_powers.log
echo "== T3 identity / norms / E formula"; nice python3 -u t3_identity.py  > logs/t3_identity.log 2>&1; tail -3 logs/t3_identity.log
echo "== T4 chirped block algorithm grid (4 parts, each < 25 min)"
for part in part1 part2 part3 part4; do
  timeout 1500 nice python3 -u t4_grid.py $part > logs/t4_grid_$part.log 2>&1; tail -1 logs/t4_grid_$part.log
done
echo "== T5 Neumann evaluation";          nice python3 -u t5_neumann.py    > logs/t5_neumann.log 2>&1;  tail -2 logs/t5_neumann.log
echo "== repro: f-input constant slip";   nice python3 repro_f_constant.py > logs/repro_f_constant.log 2>&1; cat logs/repro_f_constant.log

echo "== PR's own checks (second, non-independent signal) in a scratch export"
rm -rf scratch && mkdir scratch && git -C "$R" archive "$PIN" | tar -x -C scratch
cp scratch/certificates/fast-gaussian.json logs/fast-gaussian.orig.json
( cd scratch && nice python3 -m unittest tests.test_fast_gaussian -v ) > logs/pr_tests.log 2>&1; tail -3 logs/pr_tests.log
( cd scratch && nice python3 scripts/fast_gaussian.py ) > logs/pr_script.log 2>&1; tail -1 logs/pr_script.log
cmp scratch/certificates/fast-gaussian.json logs/fast-gaussian.orig.json && echo "certificate regenerated byte-identical"
